import { FoodEntry } from "../types/foods";

export const breakfast: FoodEntry[] = [
  {
    id: 1,
    wFrequency: 7,
    category: "mixed",
    description: "Αράβικη τόστ\n Φρούτο",
    recipe: {
      id: 11,
      category: "mixed",
      season: "all",
      name: "Αράβικη τόστ",
      description: "Ένα γευστικό πρωινό που μπορεί να ετοιμαστεί σε λίγα λεπτά.",
      serves: "1",
      ingredients: [
        { label: "Tortilla wrap ολικής", macroKey: "tortilla_wrap", baseAmountGrams: 60 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Γαλοπούλα", macroKey: "turkey_slice", baseAmountGrams: 30 },
        { label: "Φρούτο εποχής", macroKey: "seasonal_fruit", baseAmountGrams: 150 },
      ],
      instructions: [
        "Απλώνουμε τη γαλοπούλα και το τυρί στη μία πλευρά της tortilla.",
        "Διπλώνουμε την άλλη πλευρά από πάνω ώστε να καλύψει τα υλικά.",
        "Ψήνουμε στο τοστ μέχρι να λιώσει το τυρί και να γίνει τραγανή. Σερβίρουμε με φρούτο εποχής.",
      ],
    },
  },
  {
    id: 2,
    wFrequency: 7,
    category: "mixed",
    description: "100g Overnight Oats\n 20g φυστικοβούτυρο\n 15g μαρμελάδα",
    recipe: {
      id: 12,
      category: "mixed",
      season: "all",
      name: "Overnight Oats",
      description: "Μια συνταγή που μπορεί να προετοιμαστεί την προηγούμενη νύχτα. Γρήγορη, εύκολη και υγιεινή.",
      serves: "2-3",
      ingredients: [
        { label: "Βρώμη", macroKey: "oats", baseAmountGrams: 50 },
        { label: "Γάλα", macroKey: "milk", baseAmountGrams: 120 },
        { label: "Γιαούρτι", macroKey: "yogurt_plain", baseAmountGrams: 15 },
        { label: "Σπόροι chia", macroKey: "chia_seeds", baseAmountGrams: 10 },
        { label: "Μέλι", macroKey: "honey", baseAmountGrams: 7 },
        { label: "Φυστικοβούτυρο", macroKey: "peanut_butter", baseAmountGrams: 20 },
        { label: "Μαρμελάδα", macroKey: "jam", baseAmountGrams: 15 },
      ],
      instructions: [
        "Ανακατέψτε καλά όλα τα υλικά (εκτός απο τα φρούτα) σε ένα μπολ. Μπορείτε να ανακατεύεται ταυτόχρονα με την προσθήκη υλικών ώστε να επιτευχθεί ομοιογενής μίξη.",
        "Ανάλογα το μέγεθος, μπορείτε να χρησιμοποιήσετε 2-3 ποτήρια ή βαζάκια για την αποθήκευση του μείγματος. Ιδανικά αποθηκευεται σε βαζάκι που έχουν καπάκι. Αν δεν έχουμε βαζάκια με καπάκι, χρησιμοποιούμε μεμβράνη για να καλύψουμε το μπολ.",
        "Αφήνουμε το μείγμα στο ψυγείο για τουλάχιστον 5 ώρες, καλύτερα όλο το βράδυ.",
        "Σερβίρετε με φρούτα, σιρόπι σφένδαμου ή μέλι και κάνελα. Εναλλακτικά μπορείτε να προσθέσετε και καρύδια, αμύγδαλα, φιστίκια ή άλλα αγαπημένα σας toppings. Ένα απο τα αγαπημένα μου είναι το φυστικοβούτυρο με μαρμελάδα φράουλας.",
      ],
    },
  },
  {
    id: 3,
    wFrequency: 4,
    category: "mixed",
    description: "200γρ γιαούρτι 5%\n 15γρ whey\n 1 φρούτο\n 35γρ γκρανόλα\n 1 κ.γ μέλι",
    recipe: {
      id: 13,
      category: "mixed",
      season: "all",
      name: "Γιαούρτι με whey, φρούτο και γκρανόλα",
      description: "Ένα γρήγορο και θρεπτικό πρωινό με υψηλή πρωτεΐνη.",
      serves: "1",
      ingredients: [
        { label: "Γιαούρτι 5%", macroKey: "yogurt_5pct", baseAmountGrams: 200 },
        { label: "Whey protein", macroKey: "whey_protein", baseAmountGrams: 15 },
        { label: "Φρούτο εποχής", macroKey: "seasonal_fruit", baseAmountGrams: 150 },
        { label: "Γκρανόλα", macroKey: "granola", baseAmountGrams: 35 },
        { label: "Μέλι", macroKey: "honey", baseAmountGrams: 7 },
      ],
      instructions: [
        "Βάζουμε το γιαούρτι σε μπολ και ανακατεύουμε τη whey.",
        "Προσθέτουμε τη γκρανόλα, το φρούτο κομμένο σε κομμάτια και περιχύνουμε με μέλι.",
      ],
    },
  },
  {
    id: 4,
    wFrequency: 3,
    category: "mixed",
    description: "2 αυγά\n 35γρ αβοκάντο\n 1 φ. γερμανικό ψωμί\n 15γρ κότατζ",
    recipe: {
      id: 14,
      category: "mixed",
      season: "all",
      name: "Αυγά με αβοκάντο και γερμανικό ψωμί",
      description: "Πλούσιο πρωινό με αυγά, αβοκάντο και γερμανικό ψωμί.",
      serves: "1",
      ingredients: [
        { label: "Αυγά (2)", macroKey: "eggs", baseAmountGrams: 110 },
        { label: "Αβοκάντο", macroKey: "avocado", baseAmountGrams: 35 },
        { label: "Γερμανικό ψωμί", macroKey: "german_bread", baseAmountGrams: 50 },
        { label: "Κότατζ", macroKey: "cottage_cheese", baseAmountGrams: 15 },
      ],
      instructions: [
        "Ψήνουμε τα αυγά (μάτια ή ομελέτα) σε αντικολλητικό τηγάνι.",
        "Φρυγανίζουμε το γερμανικό ψωμί.",
        "Σερβίρουμε με αβοκάντο λιωμένο πάνω στο ψωμί και κότατζ.",
      ],
    },
  },
  {
    id: 5,
    wFrequency: 1,
    category: "mixed",
    description: "Πανκέικς πρωτεΐνης\n 3 ασπράδια, 1 κρόκο\n 40γρ βρώμη, 15γρ whey\n 1 μπανάνα\n 15γρ φυστικοβούτυρο, 2 κ.γ μέλι",
    recipe: {
      id: 15,
      category: "mixed",
      season: "all",
      name: "Πανκέικς πρωτεΐνης",
      description: "Πανκέικς υψηλής πρωτεΐνης με βρώμη, whey και μπανάνα.",
      serves: "1",
      ingredients: [
        { label: "Ασπράδια (3)", macroKey: "egg_white", baseAmountGrams: 100 },
        { label: "Κρόκος (1)", macroKey: "egg_yolk", baseAmountGrams: 17 },
        { label: "Βρώμη", macroKey: "oats", baseAmountGrams: 40 },
        { label: "Whey protein", macroKey: "whey_protein", baseAmountGrams: 15 },
        { label: "Μπανάνα", macroKey: "banana", baseAmountGrams: 120 },
        { label: "Φυστικοβούτυρο", macroKey: "peanut_butter", baseAmountGrams: 15 },
        { label: "Μέλι", macroKey: "honey", baseAmountGrams: 14 },
      ],
      instructions: [
        "Πολτοποιούμε τη μπανάνα σε ένα μπολ.",
        "Προσθέτουμε τα ασπράδια, τον κρόκο, τη βρώμη και τη whey. Ανακατεύουμε μέχρι να γίνει ομοιογενές μείγμα.",
        "Ψήνουμε σε αντικολλητικό τηγάνι σε μέτρια φωτιά, κάνοντας μικρά πανκέικς.",
        "Σερβίρουμε με φυστικοβούτυρο και μέλι από πάνω.",
      ],
    },
  },
];

export const lunch: FoodEntry[] = [
  {
    id: 1,
    wFrequency: 2,
    category: "legumes",
    description: "ρεβύθια με το ρύζι\n ψωμί ολικής\n σαλάτα εποχής\n 50 γρ τυρί (λίγα λιπαρά, μεχρι 14% αλλιώς 25 γρ)",
    recipe: {
      id: 1,
      category: "legumes",
      season: "all",
      name: "Ρεβύθια με το ρύζι (mock)",
      description: "Μια υγιεινή συνταγή με τα ρεβύθια να προσφέρουν πολλά θρεπτικά συστατικά.",
      serves: "1",
      ingredients: [
        { label: "Ρύζι", macroKey: "rice", baseAmountGrams: 150 },
        { label: "Ρεβύθια", macroKey: "chickpeas", baseAmountGrams: 150 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τα ρεβύθια και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Προσθέτουμε το ρύζι και αφήνουμε να βράσει για 15 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 2,
    wFrequency: 2,
    category: "legumes",
    description:
      "γίγαντες στον φούρνο\n ψωμί ολικής\n σαλάτα εποχής\n 50 γρ τυρί (λίγα λιπαρά, μεχρι 14% αλλιώς 25 γρ)",
    recipe: {
      id: 2,
      category: "legumes",
      season: "all",
      name: "Γίγαντες στον φούρνο (mock)",
      description: "Οι γίγαντες είναι ένα είδος φασολιού που περιέχει πολλές θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Γίγαντες", macroKey: "giant_beans", baseAmountGrams: 200 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τους γίγαντες και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 3,
    wFrequency: 2,
    category: "legumes",
    description: "μαυρομάτικα σαλάτα\n 2-3 μαξιμάδια\n 50 γρ τυρί (λίγα λιπαρά, μεχρι 14% αλλιώς 25 γρ)",
    recipe: {
      id: 3,
      category: "legumes",
      season: "all",
      name: "Μαυρομάτικα σαλάτα (mock)",
      description: "Μια σαλάτα που μπορεί να σε βοηθήσει να καλύψεις τις ανάγκες σου σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Μαυρομάτικα", macroKey: "black_eyed_peas", baseAmountGrams: 200 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 60 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τα μαυρομάτικα και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 4,
    wFrequency: 1,
    category: "vegetarian",
    description: "μπάμιες\n τυρι\n ψωμί",
    recipe: {
      id: 4,
      category: "vegetarian",
      season: "all",
      name: "Μπάμιες (mock)",
      description: "Οι μπάμιες είναι ένα είδος φασολιού που περιέχει πολλές θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Μπάμιες", macroKey: "okra", baseAmountGrams: 150, isFreeVegetable: true },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τις μπάμιες και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 5,
    wFrequency: 1,
    category: "vegetarian",
    description: "μανητάρια / μπριαμ\n τυρί\n ψωμι",
    recipe: {
      id: 5,
      category: "vegetarian",
      season: "all",
      name: "Μανιτάρια / Μπριάμ (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Μανιτάρια", macroKey: "mushrooms", baseAmountGrams: 150, isFreeVegetable: true },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τα μανιτάρια και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 6,
    wFrequency: 1,
    category: "vegetarian",
    description: "μελιτζάνες ιμαμ\n τυρί / γιαούρτι\n ψωμί",
    recipe: {
      id: 6,
      category: "vegetarian",
      season: "all",
      name: "Μελιτζάνες Ιμάμ (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Μελιτζάνα", macroKey: "eggplant", baseAmountGrams: 200, isFreeVegetable: true },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τις μελιτζάνες και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 7,
    wFrequency: 1,
    category: "vegetarian",
    description: "σπανακόρυζο\n  ψωμί\n τυρί",
    recipe: {
      id: 7,
      category: "vegetarian",
      season: "all",
      name: "Σπανακόρυζο (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Ρύζι", macroKey: "rice", baseAmountGrams: 150 },
        { label: "Σπανάκι", macroKey: "spinach", baseAmountGrams: 150, isFreeVegetable: true },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε το ρύζι και το νερό. Αν καταλήξει να χρειάζεται περισσότερο νερό, προσθέτουμε σιγά σιγά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 8,
    wFrequency: 3,
    category: "white_meats",
    description: "Μπιφτέκι κοτόπουλο\n Πατάτα ψητή\n Σαλάτα εποχής",
    recipe: {
      id: 8,
      category: "white_meats",
      season: "all",
      name: "Μπιφτέκια (έτοιμα)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Μπιφτέκι κοτόπουλο", macroKey: "chicken_burger", baseAmountGrams: 180 },
        { label: "Πατάτα ψητή", macroKey: "potato_baked", baseAmountGrams: 150 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Γιαούρτι", macroKey: "yogurt_plain", baseAmountGrams: 30 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ναι οκ θα μπορούσε να έχει και συνταγή, αλλά το μπιφτέκι θα έρθει απο κρεοπωλείο ή ντελίβερι.",
        "Ψήνουμε τις πατάτες σε airfryer ή φούρνο μέχρι να γίνουν τραγανές. Μπορούμε να αντικαταστήσουμε τις πατάτες με ρύζι.",
        "Φτιάχνουμε την σαλάτα μας.",
        "Σερβίρουμε τα μπιφτέκια, πατάτες, σαλάτα και τυρί.",
      ],
    },
  },
  {
    id: 9,
    wFrequency: 3,
    category: "white_meats",
    description: "κοτόπουλο στο φούρνο με λαχανικά\n σαλάτα\n τυρί",
    recipe: {
      id: 9,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο στο φούρνο με λαχανικά (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο", macroKey: "chicken_breast", baseAmountGrams: 200 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε το κοτόπουλο και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 10,
    wFrequency: 3,
    category: "white_meats",
    description: "μπουκιές κοτόπουλου με κάρυ\n ρύζι\n σαλάτα\n τυρί",
    recipe: {
      id: 10,
      category: "white_meats",
      season: "all",
      name: "Μπουκιές κοτόπουλου με κάρυ (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο", macroKey: "chicken_breast", baseAmountGrams: 200 },
        { label: "Ρύζι", macroKey: "rice", baseAmountGrams: 130 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε το κοτόπουλο και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 11,
    wFrequency: 1,
    category: "fish",
    description: "ψάρι επιλογής (σολωμός, φαγκρί ορ σαμθινγκ)\n σαλάτα",
    recipe: {
      id: 11,
      category: "fish",
      season: "all",
      name: "Ψάρι επιλογής (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Σολωμός", macroKey: "salmon", baseAmountGrams: 150 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε το ψάρι και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 12,
    wFrequency: 1,
    category: "fish",
    description: "τονοσαλάτα (100γρ κονσέρβα)\n ψωμί (τορτίγια) ή μακαρόνι",
    recipe: {
      id: 12,
      category: "fish",
      season: "all",
      name: "Τονοσαλάτα (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Τόνος σε νερό", macroKey: "tuna_in_water", baseAmountGrams: 100 },
        { label: "Tortilla wrap ολικής", macroKey: "tortilla_wrap", baseAmountGrams: 60 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τον τόνο και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 13,
    wFrequency: 1,
    category: "mixed",
    description: "ομελέτα\n σαλάτα\n τυρί\n ψωμί",
    recipe: {
      id: 13,
      category: "mixed",
      season: "all",
      name: "Ομελέτα (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Αυγά (2)", macroKey: "eggs", baseAmountGrams: 110 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Χτυπάμε τα αυγά και τα προσθέτουμε στην κατσαρόλα.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 14,
    wFrequency: 3,
    category: "white_meats",
    description: "Κοτόπουλο\n Ρύζι\n Σαλάτα εποχής",
    recipe: {
      id: 9,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο φιλέτο (έτοιμο)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο", macroKey: "chicken_breast", baseAmountGrams: 180 },
        { label: "Ρύζι", macroKey: "rice", baseAmountGrams: 130 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ναι οκ θα μπορούσε να έχει και συνταγή, αλλά το κοτόπουλο θα έρθει απο ντελίβερι ή Σούπερμαρκετ χδ.",
        "Βράζουμε το ρύζι.",
        "Φτιάχνουμε την σαλάτα μας.",
        "Σερβίρουμε το κοτόπουλο, ρύζι, σαλάτα και τυρί.",
      ],
    },
  },
  {
    id: 15,
    wFrequency: 3,
    category: "red_meats",
    description: "Πένες ολικής με κιμά\n Σαλάτα εποχής",
    recipe: {
      id: 6,
      category: "red_meats",
      season: "all",
      name: "Πένες με κιμά",
      description: "Κλασικές πένες ολικής με σάλτσα κιμά. Γρήγορο και χορταστικό γεύμα.",
      serves: "1",
      ingredients: [
        { label: "Πένες ολικής", macroKey: "whole_wheat_pasta", baseAmountGrams: 200 },
        { label: "Κιμάς", macroKey: "ground_beef", baseAmountGrams: 150 },
        { label: "Τυρί τριμένο", macroKey: "low_fat_cheese", baseAmountGrams: 20 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Βάζουμε νερό με αλάτι να βράσει για τα μακαρόνια.",
        "Σε ένα τηγάνι ζεσταίνουμε το ελαιόλαδο σε μέτρια φωτιά και σοτάρουμε κρεμμύδι μέχρι να γίνει διάφανο.",
        "Προσθέτουμε τον κιμά και τον αφήνουμε να καραμελώσει χωρίς να τον σπάσουμε. Μόλις ροδίσει καλά από κάτω, τον σπάμε και τον αναποδογυρίζουμε.",
        "Σβήνουμε με λίγο λευκό κρασί και προσθέτουμε μπαχαρικά της αρεσκείας μας. Κλασικές επιλογές: δαφνόφυλλα, κανέλα, μπαχάρι ολόκληρο. Πιο εξωτικές: κουρκουμάς, μαγιά μπύρας. Τελειώνουμε με φρεσκοτριμμένο μαύρο πιπέρι ή λίγη καυτερή σάλτσα.",
        "Προσθέτουμε τομάτα ή πελτέ, αλάτι και μαγειρεύουμε για 10-15 λεπτά μέχρι να δέσει η σάλτσα.",
        "Βράζουμε τις πένες σύμφωνα με τις οδηγίες της συσκευασίας, σουρώνουμε και ανακατεύουμε με τη σάλτσα κιμά.",
        "Σερβίρουμε με τριμμένο τυρί από πάνω και σαλάτα εποχής στο πλάι.",
      ],
    },
  },
  {
    id: 16,
    wFrequency: 3,
    category: "legumes",
    description: "Φακές\n Ψωμί ολικής",
    recipe: {
      id: 9,
      category: "legumes",
      season: "all",
      name: "Φακές",
      description: "Κλασική ελληνική φακή σούπα. Θρεπτική, χορταστική και πλούσια σε φυτικές ίνες.",
      serves: "1",
      ingredients: [
        { label: "Φακές", macroKey: "lentils", baseAmountGrams: 300 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
      ],
      instructions: [
        "Ξεπλένουμε τις φακές και τις βάζουμε σε κατσαρόλα με άφθονο νερό. Τις βράζουμε για 5 λεπτά και στραγγίζουμε (αφαιρεί τους αέρες).",
        "Σε μια κατσαρόλα σοτάρουμε ψιλοκομμένο κρεμμύδι και σκόρδο με λίγο ελαιόλαδο μέχρι να μαλακώσουν.",
        "Προσθέτουμε τις φακές, 1 δαφνόφυλλο, λίγο ξίδι και νερό να τις σκεπάσει (περίπου 3 δάχτυλα πάνω).",
        "Μαγειρεύουμε σε μέτρια φωτιά για 25-30 λεπτά μέχρι να μαλακώσουν οι φακές και να δέσει ο ζωμός.",
        "Αλατοπιπερώνουμε και σερβίρουμε με τυρί και ψωμί ολικής.",
      ],
    },
  },
  {
    id: 17,
    wFrequency: 3,
    category: "legumes",
    description: "Αρακάς\n Ψωμί ολικής",
    recipe: {
      id: 9,
      category: "legumes",
      season: "all",
      name: "Αρακάς",
      description: "Αρακάς λαδερός με πατάτα. Κλασικό ελληνικό λαδερό φαγητό.",
      serves: "1",
      ingredients: [
        { label: "Αρακάς", macroKey: "peas", baseAmountGrams: 300 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
      ],
      instructions: [
        "Σοτάρουμε ψιλοκομμένο κρεμμύδι σε λίγο ελαιόλαδο μέχρι να μαλακώσει.",
        "Προσθέτουμε τον αρακά (κατεψυγμένο ή φρέσκο) και ανακατεύουμε για 1-2 λεπτά.",
        "Προσθέτουμε λίγη τομάτα ή πελτέ, αλάτι, πιπέρι, λίγο ζάχαρη και νερό να τα σκεπάσει.",
        "Μαγειρεύουμε σε χαμηλή φωτιά για 20-25 λεπτά μέχρι ο αρακάς να μαλακώσει και να δέσει ο ζωμός.",
        "Σερβίρουμε με τυρί και ψωμί ολικής.",
      ],
    },
  },
  {
    id: 18,
    wFrequency: 1,
    category: "fish",
    description: "Πατατοσαλάτα με τόνο",
    recipe: {
      id: 18,
      category: "fish",
      season: "all",
      name: "Πατατοσαλάτα με τόνο",
      description: "Δροσερή πατατοσαλάτα με τόνο και φρέσκο κρεμμύδι. Ιδανική για γρήγορο γεύμα.",
      serves: "1",
      ingredients: [
        { label: "Τόνος σε νερό", macroKey: "tuna_in_water", baseAmountGrams: 100 },
        { label: "Πατάτα βραστή", macroKey: "potato_baked", baseAmountGrams: 70 },
        { label: "Κρέμα τυρί", macroKey: "cream_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Φρέσκο κρεμμύδι", macroKey: "spring_onion", baseAmountGrams: 30, isFreeVegetable: true },
        { label: "Λεμόνι", macroKey: "lemon", baseAmountGrams: 30, isFreeVegetable: true },
      ],
      instructions: [
        "Βράζουμε τις πατάτες με τη φλούδα τους μέχρι να μαλακώσουν (περίπου 20 λεπτά). Στραγγίζουμε και αφήνουμε να κρυώσουν.",
        "Καθαρίζουμε τις πατάτες και τις κόβουμε σε κύβους.",
        "Στραγγίζουμε τον τόνο και τον σπάμε σε κομμάτια με ένα πιρούνι.",
        "Ανακατεύουμε πατάτες, τόνο, κρέμα τυρί και ψιλοκομμένο φρέσκο κρεμμύδι. Περιχύνουμε με ελαιόλαδο και χυμό λεμονιού, αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 19,
    wFrequency: 1,
    category: "white_meats",
    description: "Φιλέτο κοτόπουλο\n Κους κους\n Σαλάτα εποχής",
    recipe: {
      id: 9,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο φιλέτο (έτοιμο)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο φιλέτο", macroKey: "chicken_breast", baseAmountGrams: 180 },
        { label: "Κους κους", macroKey: "couscous", baseAmountGrams: 150 },
        { label: "Πέστο", macroKey: "pesto_sauce", baseAmountGrams: 5 },
        { label: "Τυρί τριμένο", macroKey: "low_fat_cheese", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ναι οκ θα μπορούσε να έχει και συνταγή, αλλά το κοτόπουλο θα έρθει απο ντελίβερι ή Σούπερμαρκετ.",
        "Βράζουμε το κους κους.",
        "Φτιάχνουμε την σαλάτα μας.",
        "Σερβίρουμε το κοτόπουλο, κους κους, βάζουμε την πέστο και το τυρί πάνω στο κους κους, σαλάτα και τυρί.",
      ],
    },
  },
  {
    id: 20,
    wFrequency: 1,
    category: "white_meats",
    description: "180γρ κοτόπουλο\n 70γρ γουακαμόλε σως\n 140γρ κινόα/πλιγούρι\n ντοματίνια",
    recipe: {
      id: 20,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο με γουακαμόλε και κινόα",
      description: "Κοτόπουλο φιλέτο με σπιτικό γουακαμόλε, κινόα και ντοματίνια.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο", macroKey: "chicken_breast", baseAmountGrams: 180 },
        { label: "Γουακαμόλε", macroKey: "guacamole", baseAmountGrams: 70 },
        { label: "Κινόα", macroKey: "quinoa", baseAmountGrams: 140 },
        { label: "Ντοματίνια", macroKey: "cherry_tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Ψήνουμε το κοτόπουλο σε τηγάνι ή γκριλ με λίγο αλάτι και πιπέρι.",
        "Βράζουμε την κινόα σύμφωνα με τις οδηγίες.",
        "Σερβίρουμε το κοτόπουλο πάνω στην κινόα, με γουακαμόλε και ντοματίνια στο πλάι.",
      ],
    },
  },
  {
    id: 21,
    wFrequency: 1,
    category: "red_meats",
    description: "200γρ φιλέτο μοσχάρι\n 120γρ μπασμάτι\n 50γρ σως γιαούρτι-μουστάρδα\n σαλάτα",
    recipe: {
      id: 21,
      category: "red_meats",
      season: "all",
      name: "Φιλέτο μοσχάρι με μπασμάτι",
      description: "Φιλέτο μοσχάρι με ρύζι μπασμάτι και σως γιαούρτι-μουστάρδα.",
      serves: "1",
      ingredients: [
        { label: "Φιλέτο μοσχάρι", macroKey: "beef_fillet", baseAmountGrams: 200 },
        { label: "Ρύζι μπασμάτι", macroKey: "basmati_rice", baseAmountGrams: 120 },
        { label: "Γιαούρτι (σως)", macroKey: "yogurt_plain", baseAmountGrams: 40 },
        { label: "Μουστάρδα (σως)", macroKey: "mustard", baseAmountGrams: 10 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ψήνουμε το φιλέτο μοσχάρι σε δυνατή φωτιά, 3-4 λεπτά ανά πλευρά.",
        "Βράζουμε το μπασμάτι σύμφωνα με τις οδηγίες.",
        "Ανακατεύουμε γιαούρτι με μουστάρδα για τη σως.",
        "Σερβίρουμε με σαλάτα στο πλάι.",
      ],
    },
  },
  {
    id: 22,
    wFrequency: 1,
    category: "vegetarian",
    description: "380γρ λαδερό\n 50γρ κατίκι\n 100γρ ψητά κολοκύθι-παντζάρι κτλ",
    recipe: {
      id: 22,
      category: "vegetarian",
      season: "all",
      name: "Λαδερό με κατίκι και ψητά λαχανικά",
      description: "Λαδερό φαγητό εποχής με κατίκι και ψητά λαχανικά.",
      serves: "1",
      ingredients: [
        { label: "Λαδερό (φακές/αρακάς/φασόλια)", macroKey: "lentils", baseAmountGrams: 380 },
        { label: "Κατίκι", macroKey: "katiki_cheese", baseAmountGrams: 50 },
        { label: "Κολοκύθι ψητό", macroKey: "zucchini", baseAmountGrams: 50, isFreeVegetable: true },
        { label: "Παντζάρι ψητό", macroKey: "beetroot", baseAmountGrams: 50, isFreeVegetable: true },
      ],
      instructions: [
        "Μαγειρεύουμε το λαδερό της επιλογής μας (φακές, αρακά, φασόλια κτλ).",
        "Ψήνουμε τα λαχανικά (κολοκύθι, παντζάρι) στο φούρνο ή τηγάνι.",
        "Σερβίρουμε το λαδερό με κατίκι και τα ψητά λαχανικά στο πλάι.",
      ],
    },
  },
  {
    id: 23,
    wFrequency: 1,
    category: "red_meats",
    description: "200γρ κιμάς\n 180γρ γλυκοπατάτα\n 40γρ αβοκάντο\n 2 κ.σ γιαούρτι\n σαλάτα",
    recipe: {
      id: 23,
      category: "red_meats",
      season: "all",
      name: "Κιμάς με γλυκοπατάτα",
      description: "Κιμάς μοσχαρίσιος με ψητή γλυκοπατάτα, αβοκάντο και γιαούρτι.",
      serves: "1",
      ingredients: [
        { label: "Κιμάς", macroKey: "ground_beef", baseAmountGrams: 200 },
        { label: "Γλυκοπατάτα", macroKey: "sweet_potato", baseAmountGrams: 180 },
        { label: "Αβοκάντο", macroKey: "avocado", baseAmountGrams: 40 },
        { label: "Γιαούρτι", macroKey: "yogurt_plain", baseAmountGrams: 30 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ψήνουμε τη γλυκοπατάτα στο φούρνο μέχρι να μαλακώσει.",
        "Σοτάρουμε τον κιμά με αλάτι, πιπέρι και μπαχαρικά.",
        "Σερβίρουμε τον κιμά πάνω στη γλυκοπατάτα, με αβοκάντο και γιαούρτι.",
      ],
    },
  },
  {
    id: 24,
    wFrequency: 1,
    category: "white_meats",
    description: "220γρ κοτόπουλο σπιτική τηγανιά\n πιπεριά, κρεμμύδι\n 160γρ πατάτα ψητή γεμιστή\n γιαούρτι, πάπρικα",
    recipe: {
      id: 24,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο σπιτική τηγανιά με πατάτα γεμιστή",
      description: "Κοτόπουλο σαν σπιτική τηγανιά με πιπεριές και πατάτα ψητή γεμιστή.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο", macroKey: "chicken_breast", baseAmountGrams: 220 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 7 },
        { label: "Πατάτα ψητή", macroKey: "potato_baked", baseAmountGrams: 160 },
        { label: "Γιαούρτι", macroKey: "yogurt_plain", baseAmountGrams: 15 },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κοτόπουλο σε μπουκιές, τις πιπεριές και το κρεμμύδι σε λωρίδες.",
        "Σοτάρουμε σε τηγάνι με λίγο λάδι μέχρι να ροδίσει το κοτόπουλο.",
        "Ψήνουμε την πατάτα στο φούρνο, την ανοίγουμε και τη γεμίζουμε με γιαούρτι και πάπρικα.",
        "Σερβίρουμε την τηγανιά δίπλα στη γεμιστή πατάτα.",
      ],
    },
  },
  {
    id: 25,
    wFrequency: 1,
    category: "fish",
    description: "160γρ κριθαράκι ολικής\n 200γρ γαρίδες\n 1 κ.σ παρμεζάνα\n σαλάτα ρόκα-ντοματίνια-αγγούρι",
    recipe: {
      id: 25,
      category: "fish",
      season: "all",
      name: "Κριθαράκι ολικής με γαρίδες",
      description: "Κριθαράκι ολικής άλεσης με γαρίδες σωτέ και παρμεζάνα.",
      serves: "1",
      ingredients: [
        { label: "Κριθαράκι ολικής", macroKey: "orzo_whole_wheat", baseAmountGrams: 160 },
        { label: "Γαρίδες", macroKey: "shrimp", baseAmountGrams: 200 },
        { label: "Παρμεζάνα", macroKey: "parmesan", baseAmountGrams: 10 },
        { label: "Ρόκα", macroKey: "arugula", baseAmountGrams: 50, isFreeVegetable: true },
        { label: "Ντοματίνια", macroKey: "cherry_tomato", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Αγγούρι", macroKey: "cucumber", baseAmountGrams: 60, isFreeVegetable: true },
      ],
      instructions: [
        "Βράζουμε το κριθαράκι σύμφωνα με τις οδηγίες.",
        "Σοτάρουμε τις γαρίδες με λίγο ελαιόλαδο, σκόρδο, αλάτι και πιπέρι.",
        "Ανακατεύουμε κριθαράκι με γαρίδες, τρίβουμε παρμεζάνα από πάνω.",
        "Σερβίρουμε με σαλάτα ρόκα, ντοματίνια και αγγούρι.",
      ],
    },
  },
  {
    id: 26,
    wFrequency: 1,
    category: "fish",
    description: "250γρ σολομός\n 120γρ ρύζι\n 100γρ ψητά λαχανικά",
    recipe: {
      id: 26,
      category: "fish",
      season: "all",
      name: "Σολομός με ρύζι και ψητά λαχανικά",
      description: "Φιλέτο σολομού ψητό με ρύζι και ψητά λαχανικά.",
      serves: "1",
      ingredients: [
        { label: "Σολομός", macroKey: "salmon", baseAmountGrams: 250 },
        { label: "Ρύζι", macroKey: "rice", baseAmountGrams: 120 },
        { label: "Λαχανικά ψητά", macroKey: "salad_seasonal", baseAmountGrams: 100, isFreeVegetable: true },
      ],
      instructions: [
        "Ψήνουμε τον σολομό στο φούρνο ή γκριλ με αλάτι, πιπέρι και λεμόνι.",
        "Βράζουμε το ρύζι.",
        "Ψήνουμε τα λαχανικά (κολοκύθι, πιπεριά, μελιτζάνα) στο φούρνο.",
        "Σερβίρουμε μαζί.",
      ],
    },
  },
];

export const dinner: FoodEntry[] = [
  {
    id: 1,
    wFrequency: 3,
    category: "salad_meal",
    description: "κριτική / εποχιακή σαλάτα (φέτα / flair)",
    recipe: {
      id: 1,
      category: "salad_meal",
      season: "all",
      name: "Κριτική / Εποχιακή σαλάτα (mock)",
      description: "Μια σαλάτα που μπορεί να σε βοηθήσει να καλύψεις τις ανάγκες σου σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Τυρί φέτα", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 30 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 2,
    wFrequency: 2,
    category: "repeat_lunch",
    description: "[ίδιο με μεσημέρι σε μικρότερη ποσότητα]",
  },
  {
    id: 3,
    wFrequency: 1,
    category: "white_meats",
    description: "3 καλαμάκι κοτόπουλο\n σαλάτα\n τυρί",
    recipe: {
      id: 3,
      category: "white_meats",
      season: "all",
      name: "Καλαμάκι κοτόπουλο (mock)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Καλαμάκια κοτόπουλο", macroKey: "chicken_skewer", baseAmountGrams: 150 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 10 },
        { label: "Κρεμμύδι", macroKey: "onion", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Καρότο", macroKey: "carrot", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Πιπεριά", macroKey: "bell_pepper", baseAmountGrams: 60, isFreeVegetable: true },
        { label: "Ντομάτα", macroKey: "tomato", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε το κρεμμύδι, το καρότο, την πιπεριά και τη ντομάτα σε μικρά κομμάτια.",
        "Σε μια κατσαρόλα προσθέτουμε το ελαιόλαδο και το κρεμμύδι. Όταν το κρεμμύδι γίνει διάφανο προσθέτουμε το καρότο, την πιπεριά και τη ντομάτα.",
        "Προσθέτουμε τα καλαμάκια κοτόπουλο και το νερό. Ανακατεύουμε καλά και αφήνουμε να βράσει για 10 λεπτά.",
        "Σερβίρουμε με αλάτι και πιπέρι.",
      ],
    },
  },
  {
    id: 4,
    wFrequency: 1,
    category: "mixed",
    description: "Ομελέτα με λαχανικά επιλογής\n Ψωμί ολικής",
    recipe: {
      id: 4,
      category: "mixed",
      season: "all",
      name: "Ομελέτα με λαχανικά",
      description: "Γρήγορη ομελέτα με λαχανικά επιλογής και τυρί. Ιδανική για ελαφρύ βραδινό.",
      serves: "1",
      ingredients: [
        { label: "Αυγά (3)", macroKey: "eggs", baseAmountGrams: 165 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 50 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Ψωμί ολικής", macroKey: "whole_wheat_bread", baseAmountGrams: 60 },
        { label: "Λαχανικά επιλογής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Κόβουμε τα λαχανικά της επιλογής μας σε μικρά κομμάτια (π.χ. πιπεριά, ντομάτα, μανιτάρια, κρεμμύδι).",
        "Σε ένα αντικολλητικό τηγάνι ζεσταίνουμε το ελαιόλαδο και σοτάρουμε τα λαχανικά για 3-4 λεπτά μέχρι να μαλακώσουν.",
        "Χτυπάμε τα αυγά με λίγο αλάτι και πιπέρι και τα ρίχνουμε στο τηγάνι πάνω στα λαχανικά.",
        "Μαγειρεύουμε σε χαμηλή φωτιά. Όταν αρχίσει να πήζει, σκορπάμε το τυρί και διπλώνουμε τη μία πλευρά πάνω στην άλλη.",
        "Σερβίρουμε με ψωμί ολικής.",
      ],
    },
  },
  {
    id: 5,
    wFrequency: 3,
    category: "white_meats",
    description: "Κοτόπουλο\n Ρύζι\n Σαλάτα εποχής",
    recipe: {
      id: 9,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο φιλέτο (έτοιμο)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο", macroKey: "chicken_breast", baseAmountGrams: 150 },
        { label: "Ρύζι", macroKey: "rice", baseAmountGrams: 100 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ναι οκ θα μπορούσε να έχει και συνταγή, αλλά το κοτόπουλο θα έρθει απο ντελίβερι ή Σούπερμαρκετ χδ.",
        "Βράζουμε το ρύζι.",
        "Φτιάχνουμε την σαλάτα μας.",
        "Σερβίρουμε το κοτόπουλο, ρύζι, σαλάτα και τυρί.",
      ],
    },
  },
  {
    id: 6,
    wFrequency: 3,
    category: "red_meats",
    description: "Πένες ολικής με κιμά\n Σαλάτα εποχής",
    recipe: {
      id: 6,
      category: "red_meats",
      season: "all",
      name: "Πένες με κιμά",
      description: "Κλασικές πένες ολικής με σάλτσα κιμά. Γρήγορο και χορταστικό γεύμα.",
      serves: "1",
      ingredients: [
        { label: "Πένες ολικής", macroKey: "whole_wheat_pasta", baseAmountGrams: 180 },
        { label: "Κιμάς", macroKey: "ground_beef", baseAmountGrams: 100 },
        { label: "Τυρί τριμένο", macroKey: "low_fat_cheese", baseAmountGrams: 20 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Βάζουμε νερό με αλάτι να βράσει για τα μακαρόνια.",
        "Σε ένα τηγάνι ζεσταίνουμε το ελαιόλαδο σε μέτρια φωτιά και σοτάρουμε κρεμμύδι μέχρι να γίνει διάφανο.",
        "Προσθέτουμε τον κιμά και τον αφήνουμε να καραμελώσει χωρίς να τον σπάσουμε. Μόλις ροδίσει καλά από κάτω, τον σπάμε και τον αναποδογυρίζουμε.",
        "Σβήνουμε με λίγο λευκό κρασί και προσθέτουμε μπαχαρικά της αρεσκείας μας. Κλασικές επιλογές: δαφνόφυλλα, κανέλα, μπαχάρι ολόκληρο. Πιο εξωτικές: κουρκουμάς, μαγιά μπύρας. Τελειώνουμε με φρεσκοτριμμένο μαύρο πιπέρι ή λίγη καυτερή σάλτσα.",
        "Προσθέτουμε τομάτα ή πελτέ, αλάτι και μαγειρεύουμε για 10-15 λεπτά μέχρι να δέσει η σάλτσα.",
        "Βράζουμε τις πένες σύμφωνα με τις οδηγίες της συσκευασίας, σουρώνουμε και ανακατεύουμε με τη σάλτσα κιμά.",
        "Σερβίρουμε με τριμμένο τυρί από πάνω και σαλάτα εποχής στο πλάι.",
      ],
    },
  },
  {
    id: 7,
    wFrequency: 3,
    category: "white_meats",
    description: "Μπιφτέκι κοτόπουλο\n Πατάτα ψητή\n Σαλάτα εποχής",
    recipe: {
      id: 8,
      category: "white_meats",
      season: "all",
      name: "Μπιφτέκια (έτοιμα)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Μπιφτέκι κοτόπουλο", macroKey: "chicken_burger", baseAmountGrams: 160 },
        { label: "Πατάτα ψητή", macroKey: "potato_baked", baseAmountGrams: 150 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Γιαούρτι", macroKey: "yogurt_plain", baseAmountGrams: 30 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ναι οκ θα μπορούσε να έχει και συνταγή, αλλά το μπιφτέκι θα έρθει απο κρεοπωλείο ή ντελίβερι",
        "Ψήνουμε τις πατάτες σε airfryer ή φούρνο μέχρι να γίνουν τραγανές. Μπορούμε να αντικαταστήσουμε τις πατάτες με ρύζι.",
        "Φτιάχνουμε την σαλάτα μας",
        "Σερβίρουμε τα μπιφτέκια, πατάτες, σαλάτα και τυρί.",
      ],
    },
  },
  {
    id: 8,
    wFrequency: 3,
    category: "mixed",
    description: "FREE MEAL 🥳",
  },
  {
    id: 9,
    wFrequency: 1,
    category: "white_meats",
    description: "Φιλέτο κοτόπουλο\n Kους κους\n Σαλάτα εποχής",
    recipe: {
      id: 9,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο φιλέτο (έτοιμο)",
      description: "Ένα υγιεινό πιάτο που μπορεί να σας βοηθήσει να καλύψετε τις ανάγκες σας σε θρεπτικές ουσίες.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο φιλέτο", macroKey: "chicken_breast", baseAmountGrams: 160 },
        { label: "Κους κους", macroKey: "couscous", baseAmountGrams: 100 },
        { label: "Πέστο", macroKey: "pesto_sauce", baseAmountGrams: 5 },
        { label: "Τυρί τριμένο", macroKey: "low_fat_cheese", baseAmountGrams: 10 },
        { label: "Τυρί (εως 12% λιπαρά)", macroKey: "low_fat_cheese", baseAmountGrams: 30 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Σαλάτα εποχής", macroKey: "salad_seasonal", baseAmountGrams: 150, isFreeVegetable: true },
      ],
      instructions: [
        "Ναι οκ θα μπορούσε να έχει και συνταγή, αλλά το κοτόπουλο θα έρθει απο ντελίβερι ή Σούπερμαρκετ.",
        "Βράζουμε το κους κους.",
        "Φτιάχνουμε την σαλάτα μας.",
        "Σερβίρουμε το κοτόπουλο, κους κους, βάζουμε την πέστο και το τυρί πάνω στο κους κους, σαλάτα και τυρί.",
      ],
    },
  },
  {
    id: 10,
    wFrequency: 1,
    category: "white_meats",
    description: "200γρ κοτόπουλο\n Σαλάτα με 150γρ κολοκύθι\n 80γρ χαλούμι\n ντοματίνια\n 1 κ.γ λάδι",
    recipe: {
      id: 10,
      category: "white_meats",
      season: "all",
      name: "Κοτόπουλο με σαλάτα κολοκυθιού και χαλούμι",
      description: "Ψητό κοτόπουλο με σαλάτα από κολοκύθι, χαλούμι και ντοματίνια.",
      serves: "1",
      ingredients: [
        { label: "Κοτόπουλο", macroKey: "chicken_breast", baseAmountGrams: 200 },
        { label: "Χαλούμι", macroKey: "halloumi", baseAmountGrams: 80 },
        { label: "Ελαιόλαδο", macroKey: "olive_oil", baseAmountGrams: 5 },
        { label: "Κολοκύθι", macroKey: "zucchini", baseAmountGrams: 150, isFreeVegetable: true },
        { label: "Ντοματίνια", macroKey: "cherry_tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Ψήνουμε το κοτόπουλο σε γκριλ ή τηγάνι.",
        "Κόβουμε το κολοκύθι σε ροδέλες και το ψήνουμε ελαφρά.",
        "Ψήνουμε το χαλούμι σε τηγάνι μέχρι να ροδίσει.",
        "Σερβίρουμε σε σαλάτα με ντοματίνια και ελαιόλαδο.",
      ],
    },
  },
  {
    id: 11,
    wFrequency: 2,
    category: "dairy",
    description: "200γρ γιαούρτι\n 30γρ δημητριακά βρώμης\n 1 μήλο ή 80γρ ανανάς\n 2 κ.γ μέλι",
    recipe: {
      id: 11,
      category: "dairy",
      season: "all",
      name: "Γιαούρτι με δημητριακά και φρούτο",
      description: "Ελαφρύ βραδινό με γιαούρτι, δημητριακά βρώμης και φρούτο.",
      serves: "1",
      ingredients: [
        { label: "Γιαούρτι", macroKey: "yogurt_plain", baseAmountGrams: 200 },
        { label: "Δημητριακά βρώμης", macroKey: "oat_cereal", baseAmountGrams: 30 },
        { label: "Μήλο", macroKey: "apple", baseAmountGrams: 150 },
        { label: "Μέλι", macroKey: "honey", baseAmountGrams: 14 },
      ],
      instructions: [
        "Βάζουμε το γιαούρτι σε μπολ.",
        "Προσθέτουμε τα δημητριακά βρώμης και το μήλο κομμένο σε κομμάτια.",
        "Περιχύνουμε με μέλι.",
      ],
    },
  },
  {
    id: 12,
    wFrequency: 1,
    category: "mixed",
    description: "Ντάκος με 2 αυγά\n 60γρ παξιμάδι ολικής\n ντοματίνια\n 100γρ cottage cheese\n κάπαρη, ρίγανη",
    recipe: {
      id: 12,
      category: "mixed",
      season: "all",
      name: "Ντάκος με αυγά και cottage cheese",
      description: "Κρητικός ντάκος με αυγά, cottage cheese, ντοματίνια και κάπαρη.",
      serves: "1",
      ingredients: [
        { label: "Αυγά (2)", macroKey: "eggs", baseAmountGrams: 110 },
        { label: "Παξιμάδι ολικής", macroKey: "paximadi", baseAmountGrams: 60 },
        { label: "Cottage cheese", macroKey: "cottage_cheese", baseAmountGrams: 100 },
        { label: "Ντοματίνια", macroKey: "cherry_tomato", baseAmountGrams: 100, isFreeVegetable: true },
      ],
      instructions: [
        "Βρέχουμε ελαφρά το παξιμάδι.",
        "Ψήνουμε τα αυγά (μάτια ή βραστά).",
        "Τρίβουμε τη ντομάτα πάνω στο παξιμάδι.",
        "Σερβίρουμε με cottage cheese, κάπαρη και ρίγανη.",
      ],
    },
  },
  {
    id: 13,
    wFrequency: 1,
    category: "red_meats",
    description: "Μπουρίτο με 120γρ κιμά\n 30γρ κότατζ\n μουστάρδα, τυρί\n λαχανικά",
    recipe: {
      id: 13,
      category: "red_meats",
      season: "all",
      name: "Μπουρίτο με κιμά",
      description: "Μπουρίτο με κιμά, κότατζ, μουστάρδα και λαχανικά.",
      serves: "1",
      ingredients: [
        { label: "Tortilla wrap", macroKey: "tortilla_wrap", baseAmountGrams: 60 },
        { label: "Κιμάς", macroKey: "ground_beef", baseAmountGrams: 120 },
        { label: "Κότατζ", macroKey: "cottage_cheese", baseAmountGrams: 30 },
        { label: "Μουστάρδα", macroKey: "mustard", baseAmountGrams: 10 },
        { label: "Τυρί", macroKey: "low_fat_cheese", baseAmountGrams: 20 },
        { label: "Λαχανικά", macroKey: "salad_seasonal", baseAmountGrams: 100, isFreeVegetable: true },
      ],
      instructions: [
        "Σοτάρουμε τον κιμά με αλάτι, πιπέρι και μπαχαρικά.",
        "Απλώνουμε κότατζ και μουστάρδα στη tortilla.",
        "Βάζουμε κιμά, τυρί και λαχανικά.",
        "Τυλίγουμε σφιχτά και ψήνουμε λίγο στο τηγάνι.",
      ],
    },
  },
  {
    id: 14,
    wFrequency: 1,
    category: "fish",
    description: "150γρ σολομός\n 35γρ αβοκάντο\n 100γρ κινόα\n μαρούλι, ντοματίνια\n 1 κ.σ βινεγκρέτ",
    recipe: {
      id: 14,
      category: "fish",
      season: "all",
      name: "Σαλάτα σολομού με αβοκάντο και κινόα",
      description: "Ψητός σολομός σε σαλάτα με κινόα, αβοκάντο και βινεγκρέτ.",
      serves: "1",
      ingredients: [
        { label: "Σολομός", macroKey: "salmon", baseAmountGrams: 150 },
        { label: "Αβοκάντο", macroKey: "avocado", baseAmountGrams: 35 },
        { label: "Κινόα", macroKey: "quinoa", baseAmountGrams: 100 },
        { label: "Βινεγκρέτ", macroKey: "vinaigrette", baseAmountGrams: 15 },
        { label: "Μαρούλι", macroKey: "lettuce", baseAmountGrams: 80, isFreeVegetable: true },
        { label: "Ντοματίνια", macroKey: "cherry_tomato", baseAmountGrams: 80, isFreeVegetable: true },
      ],
      instructions: [
        "Ψήνουμε τον σολομό σε τηγάνι ή φούρνο.",
        "Βράζουμε την κινόα σύμφωνα με τις οδηγίες.",
        "Στρώνουμε μαρούλι, κινόα, αβοκάντο και ντοματίνια σε πιάτο.",
        "Τοποθετούμε τον σολομό πάνω και περιχύνουμε με βινεγκρέτ.",
      ],
    },
  },
];

export const snacks: FoodEntry[] = [
  {
    id: 1,
    wFrequency: 3,
    category: "nuts_n_fruits",
    description: "3 κ.γ ανάλατους, ωμούς ξηρούς καρπούς",
    recipe: {
      id: 1,
      category: "nuts_n_fruits",
      season: "all",
      name: "Ξηροί καρποί",
      description: "Ανάλατοι, ωμοί ξηροί καρποί.",
      serves: "1",
      ingredients: [{ label: "Ξηροί καρποί", macroKey: "dry_nuts", baseAmountGrams: 30 }],
      instructions: [],
    },
  },
  {
    id: 2,
    wFrequency: 4,
    category: "nuts_n_fruits",
    description: "Μπάρα χωρίς ή με λίγη ζάχαρη έως 200 cal\n φρούτο (ίσως)",
    recipe: {
      id: 2,
      category: "nuts_n_fruits",
      season: "all",
      name: "Μπάρα πρωτεΐνης",
      description: "Μπάρα χωρίς ή με λίγη ζάχαρη.",
      serves: "1",
      ingredients: [
        { label: "Μπάρα πρωτεΐνης", macroKey: "protein_bar", baseAmountGrams: 50 },
        { label: "Φρούτο (προαιρετικά)", macroKey: "seasonal_fruit", baseAmountGrams: 100 },
      ],
      instructions: [],
    },
  },
  {
    id: 3,
    wFrequency: 4,
    category: "dairy",
    description: "Protein yogurt (HiPRO / Arla)",
    recipe: {
      id: 3,
      category: "dairy",
      season: "all",
      name: "Protein yogurt",
      description: "Protein yogurt (HiPRO / Arla).",
      serves: "1",
      ingredients: [{ label: "Protein yogurt", macroKey: "protein_yogurt", baseAmountGrams: 190 }],
      instructions: [],
    },
  },
  {
    id: 4,
    wFrequency: 3,
    category: "dairy",
    description: "Γιαούρτι 1,5% - 2%\n 15γρ φυστικοβούτυρο\n 1 κ.σ μέλι",
    recipe: {
      id: 4,
      category: "dairy",
      season: "all",
      name: "Γιαούρτι με φυστικοβούτυρο",
      description: "Γιαούρτι 1.5% με φυστικοβούτυρο και μέλι.",
      serves: "1",
      ingredients: [
        { label: "Γιαούρτι 1.5%", macroKey: "yogurt_plain", baseAmountGrams: 150 },
        { label: "Φυστικοβούτυρο", macroKey: "peanut_butter", baseAmountGrams: 15 },
        { label: "Μέλι", macroKey: "honey", baseAmountGrams: 7 },
      ],
      instructions: [],
    },
  },
  {
    id: 5,
    wFrequency: 3,
    category: "nuts_n_fruits",
    description: "1 φρούτο + 25γρ ξηροί καρποί χωρίς αλάτι",
    recipe: {
      id: 5,
      category: "nuts_n_fruits",
      season: "all",
      name: "Φρούτο με ξηρούς καρπούς",
      description: "Φρούτο εποχής με ανάλατους ξηρούς καρπούς.",
      serves: "1",
      ingredients: [
        { label: "Φρούτο εποχής", macroKey: "seasonal_fruit", baseAmountGrams: 150 },
        { label: "Ξηροί καρποί", macroKey: "dry_nuts", baseAmountGrams: 25 },
      ],
      instructions: [],
    },
  },
  {
    id: 6,
    wFrequency: 2,
    category: "fish",
    description: "Wrap με 30γρ καπνιστό σολομό\n τυρί, 25γρ αβοκάντο\n μαρούλι, ντοματίνια",
    recipe: {
      id: 6,
      category: "fish",
      season: "all",
      name: "Wrap σολομού",
      description: "Wrap με καπνιστό σολομό, αβοκάντο, τυρί και λαχανικά.",
      serves: "1",
      ingredients: [
        { label: "Tortilla wrap", macroKey: "tortilla_wrap", baseAmountGrams: 40 },
        { label: "Καπνιστό σολομό", macroKey: "smoked_salmon", baseAmountGrams: 30 },
        { label: "Τυρί", macroKey: "low_fat_cheese", baseAmountGrams: 20 },
        { label: "Αβοκάντο", macroKey: "avocado", baseAmountGrams: 25 },
        { label: "Μαρούλι", macroKey: "lettuce", baseAmountGrams: 30, isFreeVegetable: true },
        { label: "Ντοματίνια", macroKey: "cherry_tomato", baseAmountGrams: 40, isFreeVegetable: true },
      ],
      instructions: [
        "Απλώνουμε το τυρί στη tortilla.",
        "Βάζουμε τον καπνιστό σολομό, αβοκάντο, μαρούλι και ντοματίνια.",
        "Τυλίγουμε σφιχτά.",
      ],
    },
  },
  {
    id: 7,
    wFrequency: 2,
    category: "mixed",
    description: "Choco-Banana Mug Cake\n 1 scoop whey σοκολάτα\n 35γρ βρώμη, 1 μπανάνα\n 20γρ φυστικοβούτυρο, 2 κ.γ μέλι",
    recipe: {
      id: 7,
      category: "mixed",
      season: "all",
      name: "Choco-Banana Mug Cake",
      description: "Κέικ σε κούπα με whey σοκολάτα, βρώμη και μπανάνα. Μικροκύματα 1.5 λεπτά.",
      serves: "1",
      ingredients: [
        { label: "Whey σοκολάτα", macroKey: "whey_protein", baseAmountGrams: 30 },
        { label: "Βρώμη", macroKey: "oats", baseAmountGrams: 35 },
        { label: "Μπανάνα λιωμένη", macroKey: "banana", baseAmountGrams: 120 },
        { label: "Κακάο", macroKey: "cocoa_powder", baseAmountGrams: 5 },
        { label: "Φυστικοβούτυρο", macroKey: "peanut_butter", baseAmountGrams: 20 },
        { label: "Μέλι", macroKey: "honey", baseAmountGrams: 14 },
      ],
      instructions: [
        "Λιώνουμε τη μπανάνα σε μια κούπα.",
        "Προσθέτουμε whey, βρώμη και κακάο. Ανακατεύουμε.",
        "Στο φούρνο μικροκυμάτων για 1.5 λεπτά.",
        "Σερβίρουμε με φυστικοβούτυρο και μέλι από πάνω.",
      ],
    },
  },
  {
    id: 8,
    wFrequency: 7,
    category: "dairy",
    description: "1 φρούτο + 1 σκουπ whey",
    recipe: {
      id: 8,
      category: "dairy",
      season: "all",
      name: "Φρούτο με whey shake",
      description: "Φρούτο εποχής με ένα σκουπ whey protein σε νερό.",
      serves: "1",
      ingredients: [
        { label: "Φρούτο εποχής", macroKey: "seasonal_fruit", baseAmountGrams: 150 },
        { label: "Whey protein", macroKey: "whey_protein", baseAmountGrams: 30 },
      ],
      instructions: [
        "Ανακατεύουμε τη whey σε νερό ή γάλα.",
        "Σερβίρουμε μαζί με φρούτο εποχής.",
      ],
    },
  },
];
